#!/usr/bin/env bash
# Install nginx on web server
# Nginx should be listening on port 80
# Redirects to another page

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Configure a 301 redirect for /redirect_me
sudo sed -i '/location \/ {/a \\tlocation \/redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
