#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Create a custom 404 error page

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Start Nginx service
sudo service nginx start

# Create a basic HTML file for the homepage
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html >/dev/null

# Create the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html >/dev/null

# Configure Nginx for custom 404 page
sudo sed -i 's/#error_page 404 \/404.html;/error_page 404 \/custom_404.html;/' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

