#!/usr/bin/env bash
# Script that adds HTTP response header to web servers
sudo apt-get update
sudo apt-get upgrade
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
