#!/usr/bin/env bash
#Bash script that pings 5 times an IP address passed as an argument
ip="$1"
file_name=$(basename "${BASH_SOURCE[@]}")
if ! [ "$ip" ]
then
	echo "Usage: ${file_name} {IP_ADDRESS}"
else
	ping -c 5 "${ip}"
fi
