#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
new_localhost_ip = 127.0.0.2
new_facebook_ip = 8.8.8.8
sed -i "s/localhost$/localhost $new_localhost_ip/" ~/hosts.new
sed -i "s/facebook.com$/facebook.com $new_facebook_ip/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
