#!/usr/bin/env bash
# Script that runs a web server as nginx user

# Set Nginx user to nginx
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx configuration to listen on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
